image: node:latest

variables:
  APP_STAGING: active-citizen-api-staging
  APP_PRODUCTION: active-citizen-api-production

stages:
  - build
#  - test
  - deploy

build app:
  stage: build
  script:
    - npm --version
    - npm install
    - npm build

#testing the app:
#  stage: test
#  script:
#    - npm install
#    - ng test --watch=false

deploy to staging:
  stage: deploy
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$APP_STAGING --api-key=$HEROKU_API_KEY_STAGING
  only:
    - master

deploy to production:
  stage: deploy
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$APP_PRODUCTION --api-key=$HEROKU_API_KEY_PRODUCTION
  only:
    - production
