image: gxodocker/active-citizen-dockerhub-repo:node-angular11

variables:
  APP_STAGING: active-citizen-api-staging
  APP_PRODUCTION: active-citizen-api-production

stages:
#  - build
#  - test
  - deploy

#building the app:
#  stage: build
#  script:
#    - ng --version
#    - npm --version
#    - npm install
#    - ng build --output-path dist --aot --prod
#  artifacts:
#    paths:
#      - ./dist
#
#testing the app:
#  stage: test
#  script:
#    - npm install
#    - ng test --watch=false

deploy to staging:
  stage: deploy
  image: heroku/heroku:20
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=active-citizen-api-staging --api-key=09c7301e-2394-4363-801d-9471485fd151
  only:
    - master

#deploy to production:
#  stage: deploy
#  image: heroku/heroku:20
#  script:
#    - apt-get update -qy
#    - apt-get install -y ruby-dev
#    - gem install dpl
#    - dpl --provider=heroku --app=active-citizen-api-staging --api-key=09c7301e-2394-4363-801d-9471485fd151
#  only:
#    - production
